apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret
  namespace: default
  labels:
    # Add this label to enable secret validation
    juicefs.com/validate-secret: "true"
type: Opaque
stringData:
  name: jfs
  metaurl: postgres://postgres:1234@172.17.0.1:5432/juicefs
  # If the file system has already been formatted and you don't want to format it again in the pod, 
  # you can leave the `storage` and  `bucket` parameters blank.
  storage: minio
  bucket: http://172.17.0.1:9000/llm-models
  access-key: minioadmin
  secret-key: minioadmin
  # Inject environment variables, e.g. timezone (UTC by default), or encryption paraphrase
  # envs: "{TZ: Asia/Shanghai, JFS_RSA_PASSPHRASE: xxx}"
  # Options for juicefs format
  # format-options: trash-days=1,block-size=4096
  # If encryption is enabled for the file system, the RSA private key needs to be included as well
  # encrypt_rsa_key: xxx