apiVersion: v1
kind: PersistentVolume
metadata:
  name: "qwen2-5-coder-3b-instruct"
  labels:
    model: "qwen2-5-coder-3b-instruct"
spec:
  capacity:
    storage: "20Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/trucdnd/Documents/models/"

